apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myrunstreak.fullname" . }}-frontend
  labels:
    {{- include "myrunstreak.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myrunstreak.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "myrunstreak.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      imagePullSecrets:
        - name: myrunstreak-ghcr
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myrunstreak.fullname" . }}-frontend
  labels:
    {{- include "myrunstreak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "myrunstreak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
