#!/usr/bin/env python3
"""REST-based restore of an STK data backup into a LOCAL Supabase (SB-224).

Loads a gzip'd JSON dump produced by ``backup_database.py`` into the local
Supabase over the REST API. Clears the run-data tables (child → parent) then
re-inserts them (parent → child), sanitizing foreign keys so only rows that
resolve against local ``users`` survive.

LOCAL ONLY: this truncates tables, so it refuses to run against any URL that is
not 127.0.0.1 / localhost.

Ordering contract (run these BEFORE this script):
    1. `jt supabase sync-users stk` — recreates silverbeer.io@gmail.com locally
       with the SAME prod uid, so runs.user_id resolves.
Then AFTER this script:
    2. `scripts/seed_local_users.py` — owns the coach/athlete test data.

Env:
    SUPABASE_URL          http://127.0.0.1:54321 (local)
    SUPABASE_SERVICE_KEY  local service_role key (SUPABASE_SERVICE_ROLE_KEY also accepted)

Usage:
    SUPABASE_URL=... SUPABASE_SERVICE_KEY=... \
      uv run --project backend python scripts/restore_database.py --latest --backup-dir ~/backups/stk
"""

from __future__ import annotations

import argparse
import gzip
import json
import sys
from pathlib import Path

from _db_env import is_local, require_env

from supabase import Client, create_client

# Restore order = FK-parent order (parents first). Clearing runs in reverse.
#
# Per table:
#   pk        primary-key column used to clear and to track surviving rows
#   parents   [(fk_col, parent_table)] — row dropped if fk not among survivors
#   upsert    merge on the pk instead of clear+insert (reference / shared data)
#   auth_gate keep a row only if its pk exists in local auth.users — used for
#             public.users so we mirror prod identity WITHOUT creating a
#             public.users row that has no matching auth user
#
# public.users is upserted (never cleared) so the seeded local test users
# (coach@/a1@…) survive; only prod users that `jt sync-users` recreated in local
# auth get added. runs/goals/etc. then reference survivors["users"], which is
# the union of the pre-existing local users and the ones just restored.
RESTORE_ORDER: list[dict] = [
    {"table": "users", "pk": "user_id", "upsert": True, "auth_gate": True},
    {"table": "user_sources", "pk": "id", "parents": [("user_id", "users")]},
    {"table": "metric_types", "pk": "key", "upsert": True},
    {
        "table": "runs",
        "pk": "id",
        "parents": [("user_id", "users"), ("source_id", "user_sources")],
    },
    {"table": "splits", "pk": "id", "parents": [("run_id", "runs")]},
    {
        "table": "goals",
        "pk": "id",
        "parents": [("user_id", "users"), ("source_id", "user_sources")],
    },
    # source='run' entries are regenerated by the project_run_to_metric_entry
    # trigger when runs are inserted above — restoring them too collides on the
    # partial unique index (user_id,metric_key,source,external_id). Skip them;
    # keep only manual / non-run entries.
    {
        "table": "metric_entries",
        "pk": "id",
        "parents": [("user_id", "users")],
        "skip_source": "run",
    },
    {"table": "metric_goals", "pk": "id", "parents": [("user_id", "users")]},
]

BATCH_SIZE = 100
PAGE_SIZE = 1000


def existing_user_ids(sb: Client) -> set[str]:
    """user_id of every public.users row already present locally (test users)."""
    result = sb.table("users").select("user_id").execute()
    return {row["user_id"] for row in (result.data or [])}


def local_auth_ids(sb: Client) -> set[str]:
    """Every auth.users id present locally (populated by `jt sync-users`)."""
    ids: set[str] = set()
    page = 1
    while True:
        resp = sb.auth.admin.list_users(page=page, per_page=1000)
        users = resp if isinstance(resp, list) else getattr(resp, "users", [])
        if not users:
            break
        ids.update(str(u.id) for u in users)
        if len(users) < 1000:
            break
        page += 1
    return ids


def clear_table(sb: Client, table: str, pk: str) -> None:
    """Delete every row from a table, paginating to handle >1000 rows."""
    total = 0
    while True:
        result = sb.table(table).select(pk).limit(PAGE_SIZE).execute()
        rows = result.data or []
        if not rows:
            break
        ids = [r[pk] for r in rows]
        for i in range(0, len(ids), BATCH_SIZE):
            chunk = ids[i : i + BATCH_SIZE]
            sb.table(table).delete().in_(pk, chunk).execute()
            total += len(chunk)
        if len(rows) < PAGE_SIZE:
            break
    print(f"  ✓ cleared {total} from {table}")


def sanitize(
    rows: list[dict], spec: dict, auth_ids: set[str], survivors: dict[str, set]
) -> list[dict]:
    """Drop rows whose auth gate / parent FKs don't resolve locally."""
    pk = spec["pk"]
    auth_gate = spec.get("auth_gate")
    parents = spec.get("parents", [])
    kept: list[dict] = []
    dropped = 0
    for row in rows:
        if auth_gate and row.get(pk) not in auth_ids:
            dropped += 1
            continue
        if any(row.get(col) not in survivors[parent] for col, parent in parents):
            dropped += 1
            continue
        kept.append(row)
    if dropped:
        print(f"  ℹ️  dropped {dropped} row(s) with FK not present locally")
    return kept


def restore_table(
    sb: Client, spec: dict, rows: list[dict], auth_ids: set[str], survivors: dict[str, set]
) -> None:
    table, pk = spec["table"], spec["pk"]
    if not rows:
        print(f"Restoring {table}: no data")
        survivors.setdefault(table, set())
        return

    skip_source = spec.get("skip_source")
    if skip_source:
        before = len(rows)
        rows = [r for r in rows if r.get("source") != skip_source]
        if before != len(rows):
            print(
                f"  ℹ️  skipped {before - len(rows)} {table} row(s) with source={skip_source} (trigger-owned)"
            )

    rows = sanitize(rows, spec, auth_ids, survivors)
    # Union so pre-seeded survivors (e.g. existing local users) are preserved.
    survivors[table] = survivors.get(table, set()) | {row[pk] for row in rows}
    if not rows:
        print(f"Restoring {table}: nothing left after sanitize")
        return

    print(f"Restoring {table} ({len(rows)} rows)...")
    inserted = 0
    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i : i + BATCH_SIZE]
        if spec.get("upsert"):
            sb.table(table).upsert(batch, on_conflict=pk).execute()
        else:
            sb.table(table).insert(batch).execute()
        inserted += len(batch)
    print(f"  ✅ {inserted} rows into {table}")


def restore(sb: Client, backup_file: Path) -> None:
    with gzip.open(backup_file, "rt", encoding="utf-8") as f:
        payload = json.load(f)
    if "tables" not in payload:
        raise SystemExit("❌ invalid backup file: no 'tables' key")

    tables = payload["tables"]
    info = payload.get("backup_info", {})
    print(f"Restoring from {backup_file.name} (created {info.get('created_at', '?')})")
    print("=" * 50)

    # Clear child → parent. Upserted tables (users, metric_types) are NOT
    # cleared: users keeps the seeded local test users, metric_types is
    # migration-seeded reference data referenced by metric_entries/goals.
    print("🧹 Clearing existing run-data...")
    for spec in reversed(RESTORE_ORDER):
        if spec.get("upsert"):
            continue
        clear_table(sb, spec["table"], spec["pk"])

    # Gate public.users to local auth. Seed survivors["users"] with the users
    # that already exist locally (test users) so their run-data still matches
    # even though we only *add* prod users on top.
    auth_ids = local_auth_ids(sb)
    survivors: dict[str, set] = {"users": existing_user_ids(sb)}
    print(f"🔍 {len(auth_ids)} local auth user(s); {len(survivors['users'])} existing public.users")
    if not auth_ids:
        print(
            "  ⚠️  no local auth users — run `jt supabase sync-users stk` first, "
            "or prod users (and their run-data) will be dropped."
        )

    print("📥 Restoring parent → child...")
    for spec in RESTORE_ORDER:
        restore_table(sb, spec, tables.get(spec["table"], []), auth_ids, survivors)

    print("=" * 50)
    restored = sum(len(s) for s in survivors.values())
    print(f"✅ Restore complete: {restored} rows")


def find_latest(backup_dir: Path) -> Path | None:
    candidates = sorted(backup_dir.glob("stk_backup_*.json.gz"), reverse=True)
    return candidates[0] if candidates else None


def main() -> None:
    parser = argparse.ArgumentParser(description="STK REST data restore (SB-224)")
    parser.add_argument("backup_file", nargs="?", help="Backup file (path or name)")
    parser.add_argument("--latest", action="store_true", help="Use newest backup in --backup-dir")
    parser.add_argument(
        "--backup-dir",
        type=Path,
        default=Path.home() / "backups" / "stk",
        help="Directory holding backups (default: ~/backups/stk)",
    )
    args = parser.parse_args()

    url, key = require_env()
    if not is_local(url):
        raise SystemExit(
            f"REFUSING: SUPABASE_URL is not local ({url}). "
            "Restore truncates tables and is local-only."
        )

    if args.latest:
        backup_file = find_latest(args.backup_dir)
        if not backup_file:
            raise SystemExit(f"❌ no backups found in {args.backup_dir}")
    elif args.backup_file:
        backup_file = Path(args.backup_file)
        if not backup_file.is_absolute() and "/" not in args.backup_file:
            backup_file = args.backup_dir / args.backup_file
    else:
        raise SystemExit("❌ specify a backup file or --latest")

    if not backup_file.exists():
        raise SystemExit(f"❌ backup file not found: {backup_file}")

    sb = create_client(url, key)
    try:
        restore(sb, backup_file)
    except Exception as e:  # noqa: BLE001 — top-level guard, surface and exit
        print(f"❌ Restore failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
